.TH "manpageeditor" 1 "20 ноября 2016" "ManPageEditor 0.1.1" "Краткая справка"

.SH НАЗВАНИЕ

.B Manpage Editor - Редактор справочных страниц (man pages).

.SH СИНТАКСИС
manpageeditor \fIFILE\fR

.SH ОПИСАНИЕ

Графический интерфейс для создания и редактирования справочных страниц (man pages).
Для каждого раздела справочной страницы имеется соответствующая вкладка.
Возможен импорт и предпросмотр страниц.

.SH ФАЙЛЫ

$HOME/.ManPageEditor/editor.rc
.br
$HOME/.ManPageEditor/editor.window.rc
.br

.SH АВТОР

K.D.Hedger
Сообщения об ошибках и предложения направлять:
.br
<kdhedger68713@gmail.com>
.br

.SH СМОТРИТЕ

.B Xfce Theme Manager:
.br
http://xfce-look.org/content/show.php/Xfce-Theme-Manager?content=149647
.br
.B Xfce4 Composite Editor:
.br
http://gtk-apps.org/content/show.php/?content=149523
.br
.B KKEdit:
.br
http://gtk-apps.org/content/show.php/KKEdit?content=158161
.br
.B GtkSu:
.br
http://gtk-apps.org/content/show.php/GtkSu?content=158974

.SH ПЕРЕВОД
Виктор Набатов <greenray.spb@gmail.com>
